### ISSUE TITLE
Stale state when moving from one screen to another

### ISSUE THREAD

**Issue by aquibbaig** [ankitjena/literature#47]
Reload the "GameScreen" screen and you will find error corresponding to the build of "WaitingPage" state. That's because `playersList` field in the "WaitingPage" is null. Ideally, these screens should be independent and shouldn't re-render on reload.

**Comment by StrangeNoob** [comment]
@aquibbaig if anyone is not working on this I would like to give it a try

**Comment by aquibbaig** [comment]
Go ahead.

**Comment by aquibbaig** [comment]
@StrangeNoob Fixed with #54.
